CMS_HOST: studio.local.openedx.io
CMS_OAUTH2_SECRET: mGOpvOLxzmlVJABt8JMTz7SK
CONTACT_EMAIL: tonettedevera061405@gmail.com
ENABLE_HTTPS: false
ID: JY6EmNIhpS0blV9Nwpjg3g9N
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAkNdh+v5fpioQbajMMn1HMGwJP734UIUZKEGZyz+Ca4Cjn10f

  3O6jSANlsGPFfIepQkirlKIB9UbHdyclJC8h3rGN30GBQ41LYaEewhrvAVUnolVH

  AOWQ5VK5T7oskw8LWoddCc7EUVFb3/2rI2Jh/NE2bdNO+fUDODlOKZ/NiLlVWi6k

  2mEHuKBQq6YQUxUFiNcE+IOgHgZAISRv0GpNGvfIkVb/4wiSech5hEdzBs90I+oB

  BVcUIsBmEsPxZKs8P5EuyWpgrFws5Wueocy0nMEyo8S+6qVTj7ZtKtMbsz+BgaYu

  23KeWVyLy1IgeBDWHIfBskAzPtQNX0hR6dHukwIDAQABAoIBAAMe578z+OvlRrGg

  Ej166pPkdhwUANsInEEOme1dGmssWrWVyYxL4bLwCVMZXqZbVDXXu3gB1ox8figB

  sA2bAfyGxx1VUpk+bwOwZUHhS4mt3EHA/8NDCmjL07ssRHFPqHrrMVbkzjZUzDDf

  QL55np0+BU5v/mLQzmOquxXHvpEiEWPjRwVWDJxdwgepBklr6W+04ne1gmmYHXpP

  /qrAVFi/QHf7HuFVJjYRDnCK50R1y+S94NrGQFwOvN6Yimyvk1xrlF2nQLaDXTaj

  OzwM7eug/hBMFPlCIu/0081WkvXY/cMRMyoLM8VTjgAQsdPOCAFbhPtzsolXePrD

  Fncsx9kCgYEAtY8sFp7GvKB8yucZZsKn3iUZBvl1+/7qaCZLgAEKFk0g0cuo0jHP

  +0+xoUTfVPRGShDC3kvUmnz7QuqDtuk0Icwip0lEjdTHhYkmRSeIdTLylSP1yQux

  f9Vbp0W9pi02UQASoZBJ+lT44YYoHiJI66H7VMocpdWfFx4RcHkl7YUCgYEAzDo4

  +oCucbaCGuHSyDeqxNDim8XAFZpxG/mdD4gBgeqMfU3doDLMxowhi19s6t0M3Chc

  4aIGg0colm+oyjocqYMjPlXRvS5C3oshAEWDk9KI7GWzgD4PxZHoVzjM/WBwQRR1

  sxa0w902nBXveDv+SaQVKB9qMyt17ct64KZpezcCgYB+K1OBGK+VD5YJTtXJIoaT

  ioY84YjLKNfuroYTGyXOX6TqBjR4daNJypTvNDRbDjH2cHVrE5lYDnhxhRUpPCA9

  SGXgiLr6MR7CPo/4yMM8Zr5LRCUepGCiLDu4H2/ulkbDvWA1JFc0fm5CEv+4CS1R

  ikxlHNsRp0UaRIvr9FSWHQKBgFmehxhuVZ6y3z8ar9uKihaaL4b57UPNpSsIi4Kg

  RUEUgxgNjl7ZTAEoxyOY+XvLCvSlhbTB3CfJlycE0sYDYEaGtHWLRWHGJjPwS8gJ

  uSaqMcnDC1UQZu1lDNcRpurdYgU9DDVNln+I2IkAGzjg4sLADUSxHHJd9P8n1sE0

  ZX9bAoGAPClIWVHgIi+zSUMlH0hqxg9yz9Z9DmuiDji52XnBmq5L6AfCodVv5c1u

  OpAL6l1jvi2CBfzVjzOsKw4HKorQxhdw/z95PuR3pyemfJHQNWOlE/jq0lubdNSv

  inTPUWaIH4oNQbMRly67MGfnrGlgJomObskK1n7Xqszi7QwBzk4=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.openedx.io
MEILISEARCH_API_KEY: 23e9d87afd850f8258cb71f6a580292688e12594e3cffbc5f7a7249ed1232103
MEILISEARCH_API_KEY_UID: 1925ae8e-4fdf-4e0a-8e42-a61630fe8341
MEILISEARCH_MASTER_KEY: aPAjrPFaNCSKF6vIRy2RRpQe
MYSQL_ROOT_PASSWORD: TSmktpSs
OPENEDX_MYSQL_PASSWORD: dfjHIaXP
OPENEDX_SECRET_KEY: 5FANuWOsCLM9frK4K2D17OOo
PLATFORM_NAME: ICS 401-A edX
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
